application: myblog-167810
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: .*
  script: NYW_blog.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"

